# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "177ac2a00973ba8fc0c323f490150da3"
name = "kritic-app"
handle = "kritic-app"
application_url = "https://commonwealth-bowling-emerald-organisations.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chandstest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://commonwealth-bowling-emerald-organisations.trycloudflare.com/auth/callback",
  "https://commonwealth-bowling-emerald-organisations.trycloudflare.com/auth/shopify/callback",
  "https://commonwealth-bowling-emerald-organisations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
