import mongoose from 'mongoose';
if (mongoose.models['review_discount_settings']) {
  // Delete the existing model
  delete mongoose.models['review_discount_settings'];
}


const reviewDiscountSettingsSchema = new mongoose.Schema({

  shop_id: { type: mongoose.Schema.Types.ObjectId, ref: 'shop_details', required: true },
  isDiscountEnabled: { type: Boolean, default: true },
  isSameDiscount: { type: Boolean, default: true },
  sameDiscountType: { type: String, default: 'percentage' },
  sameDiscountValue: { type: Number, default: 0 },
  differentDiscountPhotoType: { type: String, default: 'percentage' },
  differentDiscountPhotoValue: { type: Number, default: 0 },
  differentDiscountVideoType: { type: String, default: 'percentage' },
  differentDiscountVideoValue: { type: Number, default: 0 },
  isAutoGeneratedDiscount: { type: Boolean, default: true },
  expiredAfter: { type: String, default: '' },
  reviewType: { type: String, default: 'both' },
  discountCode: { type: String, default: '' },
  defaultDiscountType: { type: String, default: '' },
  defaultDiscountValue: { type: Number, default: '' },
  discountId: { type: String, default: '' },
  defaultDiscountExpiredAt: { type: Date, default: null },
  
}, {
  timestamps: true
});

const reviewDiscountSettings = mongoose.model('review_discount_settings', reviewDiscountSettingsSchema);
export default reviewDiscountSettings;
