import mongoose from 'mongoose';
if (mongoose.models['review_discount_settings']) {
  // Delete the existing model
  delete mongoose.models['review_discount_settings'];
}


const reviewDiscountSettingsSchema = new mongoose.Schema({
    
    shop_id: {type: mongoose.Schema.Types.ObjectId, ref: 'shop_details', required: true },
    isDiscountEnabled : {type : Boolean, default : true},
    isSameDiscount : {type : Boolean, default : true},
    sameDiscountType : {type : String, default : 'percentage'},
    sameDiscountValue : {type : String},
    differentDiscountPhotoType : {type : String, default : 'percentage'},
    differentDiscountPhotoValue : {type : String},
    differentDiscountVideoType : {type : String, default : 'percentage'},
    differentDiscountVideoValue : {type : String},
    isAutoGeneratedDiscount : {type : Boolean, default : true},
    expiredAfter : {type : String},
    reviewType : {type : String, default : 'both'},
    discountCode : {type : String}
},{
    timestamps: true
});

const  reviewDiscountSettings = mongoose.model('review_discount_settings', reviewDiscountSettingsSchema);
export default reviewDiscountSettings;
